version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:80"
#    environment:
#      - BOT_TOKEN=${BOT_TOKEN}
#      - ADMIN_ID=${ADMIN_ID}
#
#59404714
#7925998018:AAF3IonF_5oB6FZUQhzBkblQ8DT1paeUBjA
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
