version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "9000:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
