version: "3.8"
services:
  db:
    image: postgres:17
    container_name: db
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7
    container_name: redis
    env_file: .env
    command:
      - redis-server
      - --requirepass
      - "${REDIS_PASSWORD}"
      - --appendonly
      - "yes"
      - --appendfsync
      - "everysec"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file: .env
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    restart: always

  backend:
    build: ./backend
    container_name: backend
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
    networks:
      - app-network
    restart: always

  bot:
    build: ./bot
    container_name: bot
    env_file: .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  proxy:
    build: ./nginx
    container_name: proxy
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - app-network
    restart: always

  mail:
    image: mailserver/docker-mailserver:latest
    container_name: mail
    env_file:
      - .env
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./mailserver/config/:/tmp/docker-mailserver/
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    networks:
      - app-network
    restart: always

  webmail:
    image: interlegis/alpine-rainloop:latest
    container_name: webmail
    env_file:
      - .env
    volumes:
      - webmaildata:/var/www/rainloop/data
      - ./mailserver/config/apache.conf:/etc/apache2/conf.d/server-name.conf:ro
    depends_on:
      - mail
    networks:
      - app-network
    restart: always

volumes:
  db_data:
    external: true
    name: yanda_shop_db_data
  redis_data:
    external: true
    name: yanda_shop_redis_data
  minio_data:
    external: true
    name: yanda_shop_minio_data
  maildata:
    name: yanda_shop_mail_data
  mailstate:
    name: yanda_shop_mail_state
  webmaildata:
    name: yanda_shop_webmail_data

networks:
  app-network:
    driver: bridge
