version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "9000:80"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  bot:
    build: ./bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
    depends_on:
      - backend
    x-tw-secrets:
      - BOT_TOKEN
      - ADMIN_ID