version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend

  bot:
    build: ./bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge
    name: telegram_app_network