version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - app-network
    restart: always

  bot:
    build: ./bot
    env_file: .env
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

  proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
    restart: always

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    env_file: .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  redis_data:
