version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - BOT_TOKEN=your-telegram-bot-token
      - ADMIN_ID=your-admin-id
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
