version: "3.8"
services:
  db:
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7
    env_file: .env
    command:
      - redis-server
      - --requirepass
      - "${REDIS_PASSWORD}"
      - --appendonly
      - "yes"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: always

  minio:
    image: minio/minio:latest
    env_file: .env
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    restart: always

  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
    networks:
      - app-network
    restart: always

  bot:
    build: ./bot
    env_file: .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  proxy:
    build: ./nginx
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - app-network
    restart: always

volumes:
  db_data:
    external: true
  redis_data:
    external: true
  minio_data:
    external: true

networks:
  app-network:
    driver: bridge
