version: "3.8"

services:
  backend:
    build: ./backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  bot:
    build: ./bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge