"""add avatar_url in Users

Revision ID: 0598f3d11ecb
Revises: 77596e1430f6
Create Date: 2025-07-01 09:17:10.077063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0598f3d11ecb'
down_revision = '77596e1430f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=100), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
