"""edit column names of size

Revision ID: 2030dbde53de
Revises: dd5e558261b3
Create Date: 2025-06-24 01:08:39.707058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2030dbde53de'
down_revision = 'dd5e558261b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_label', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('width_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('depth_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('size_category', sa.Integer(), nullable=True))
        batch_op.drop_column('height_mm')
        batch_op.drop_column('size_guide_url')
        batch_op.drop_column('depth_mm')
        batch_op.drop_column('width_mm')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chest_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('size_category', sa.Integer(), nullable=True))
        batch_op.drop_column('height_mm')
        batch_op.drop_column('size_guide_url')
        batch_op.drop_column('width_mm')

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_category', sa.Integer(), nullable=True))
        batch_op.drop_column('size_guide_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_guide_url', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('size_category')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size_guide_url', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('size_category')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('chest_cm')

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('depth_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('size_guide_url', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height_mm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('size_category')
        batch_op.drop_column('depth_cm')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('width_cm')
        batch_op.drop_column('size_label')

    # ### end Alembic commands ###
