"""add default values in Users

Revision ID: 2e88b79109d2
Revises: 80b7d4dd4260
Create Date: 2025-08-10 02:50:54.284771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e88b79109d2'
down_revision = '80b7d4dd4260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('delivery_price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('mailing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('loyalty_points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_spent',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('order_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_spent',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('loyalty_points',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mailing',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('delivery_price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
