"""add column count_in_stock

Revision ID: 2eb8da95def7
Revises: c6d67282d1d9
Create Date: 2025-05-30 18:48:02.502800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb8da95def7'
down_revision = 'c6d67282d1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_in_stock', sa.Integer(), nullable=True))

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_in_stock', sa.Integer(), nullable=True))

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_in_stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_column('count_in_stock')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_column('count_in_stock')

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.drop_column('count_in_stock')

    # ### end Alembic commands ###
