"""add addresses select column

Revision ID: 395770c5fa2e
Revises: 75bfe4da00dd
Create Date: 2025-08-06 17:59:06.116380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395770c5fa2e'
down_revision = '75bfe4da00dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('select', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('select')

    # ### end Alembic commands ###
