"""delete phone columns in users

Revision ID: 3f47f418edc7
Revises: 89aab35782e4
Create Date: 2025-08-02 22:12:22.044876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f47f418edc7'
down_revision = '89aab35782e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
