"""add delivery_date column in orders

Revision ID: 3fad4b17a8e1
Revises: 96edfcb9254b
Create Date: 2025-08-08 07:36:14.917429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fad4b17a8e1'
down_revision = '96edfcb9254b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('canceled_at')

    # ### end Alembic commands ###
