"""add Users

Revision ID: 580593c4565d
Revises: 5a15c360f283
Create Date: 2025-06-04 14:00:51.139765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '580593c4565d'
down_revision = '5a15c360f283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('visitors')
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.drop_constraint('accessories_sku_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_accessories_sku'), ['sku'], unique=True)

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_constraint('clothing_sku_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_clothing_sku'), ['sku'], unique=True)

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_constraint('shoes_sku_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_shoes_sku'), ['sku'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shoes_sku'))
        batch_op.create_unique_constraint('shoes_sku_key', ['sku'])

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clothing_sku'))
        batch_op.create_unique_constraint('clothing_sku_key', ['sku'])

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accessories_sku'))
        batch_op.create_unique_constraint('accessories_sku_key', ['sku'])

    op.create_table('visitors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('visit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='visitors_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
