"""add updated_at in categories

Revision ID: 5a15c360f283
Revises: 2eb8da95def7
Create Date: 2025-06-03 14:54:02.775197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a15c360f283'
down_revision = '2eb8da95def7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
