"""edit columns name and type

Revision ID: 6a1f9c764c05
Revises: 96b007399a4a
Create Date: 2025-05-29 13:32:18.438008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1f9c764c05'
down_revision = '96b007399a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('depth_mm', sa.Float(), nullable=True))

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height_mm', sa.Float(), nullable=True))

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_label', sa.Float(), nullable=True))
        batch_op.alter_column('depth_mm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('width_mm')
        batch_op.drop_column('height_mm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_mm', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('width_mm', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('depth_mm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('size_label')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_column('height_mm')
        batch_op.drop_column('width_mm')

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.drop_column('depth_mm')
        batch_op.drop_column('height_mm')
        batch_op.drop_column('width_mm')

    # ### end Alembic commands ###
