"""add new columns in Users

Revision ID: 7714d754cfa7
Revises: a83991e4b257
Create Date: 2025-06-28 04:55:42.427947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7714d754cfa7'
down_revision = 'a83991e4b257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('client_text1',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('shop_response',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('link_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.Enum(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mailing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_spent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_visit', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_visit')
        batch_op.drop_column('order_count')
        batch_op.drop_column('total_spent')
        batch_op.drop_column('loyalty_points')
        batch_op.drop_column('mailing')
        batch_op.drop_column('role')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('phone_verified')
        batch_op.drop_column('phone')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('email')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('link_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('shop_response',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('client_text1',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
