"""remove client_id from reviews, add client_name

Revision ID: 77596e1430f6
Revises: 7714d754cfa7
Create Date: 2025-06-30 09:14:55.043986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77596e1430f6'
down_revision = '7714d754cfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('reviews_client_id_fkey'), type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('reviews_client_id_fkey'), 'users', ['client_id'], ['user_id'])
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
