"""add pvz columns

Revision ID: 7d563dcfea3f
Revises: e3a3051c751a
Create Date: 2025-09-08 06:39:51.280134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d563dcfea3f'
down_revision = 'e3a3051c751a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pvz_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pvz_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pvz_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pvz_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pvz_lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('pvz_lon')
        batch_op.drop_column('pvz_lat')
        batch_op.drop_column('pvz_address')
        batch_op.drop_column('pvz_name')
        batch_op.drop_column('pvz_id')

    # ### end Alembic commands ###
