"""change columns in orders

Revision ID: 80b7d4dd4260
Revises: 3fad4b17a8e1
Create Date: 2025-08-09 04:47:47.624517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80b7d4dd4260'
down_revision = '3fad4b17a8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('transferred_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transferred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.alter_column('processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###
