"""change indexed columns

Revision ID: 89aab35782e4
Revises: cbab6936a243
Create Date: 2025-07-29 13:21:35.591247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89aab35782e4'
down_revision = 'cbab6936a243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accessories_sku'))
        batch_op.drop_index(batch_op.f('ix_accessories_world_sku'))
        batch_op.create_index(batch_op.f('ix_accessories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_size_label'), ['size_label'], unique=False)

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clothing_sku'))
        batch_op.drop_index(batch_op.f('ix_clothing_world_sku'))
        batch_op.create_index(batch_op.f('ix_clothing_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_size_label'), ['size_label'], unique=False)

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shoes_sku'))
        batch_op.drop_index(batch_op.f('ix_shoes_world_sku'))
        batch_op.create_index(batch_op.f('ix_shoes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_size_label'), ['size_label'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shoes_size_label'))
        batch_op.drop_index(batch_op.f('ix_shoes_name'))
        batch_op.create_index(batch_op.f('ix_shoes_world_sku'), ['world_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_sku'), ['sku'], unique=False)

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clothing_size_label'))
        batch_op.drop_index(batch_op.f('ix_clothing_name'))
        batch_op.create_index(batch_op.f('ix_clothing_world_sku'), ['world_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_sku'), ['sku'], unique=False)

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accessories_size_label'))
        batch_op.drop_index(batch_op.f('ix_accessories_name'))
        batch_op.create_index(batch_op.f('ix_accessories_world_sku'), ['world_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###
