"""add delivery order columns

Revision ID: 96edfcb9254b
Revises: 4dc23c786bab
Create Date: 2025-08-08 05:38:25.153083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96edfcb9254b'
down_revision = '4dc23c786bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('assembled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('transferred_at')
        batch_op.drop_column('assembled_at')
        batch_op.drop_column('purchased_at')

    # ### end Alembic commands ###
