"""new table Reviews

Revision ID: a83991e4b257
Revises: ef93b5dc5b2c
Create Date: 2025-06-27 07:57:46.001470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83991e4b257'
down_revision = 'ef93b5dc5b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('client_text1', sa.Text(), nullable=True),
    sa.Column('shop_response', sa.Text(), nullable=True),
    sa.Column('client_text2', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
