"""add variant_sku in tables

Revision ID: b9e04dc6eacb
Revises: 3b624ea5c568
Create Date: 2025-06-11 18:19:30.962613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e04dc6eacb'
down_revision = '3b624ea5c568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_sku', sa.String(length=100), nullable=False))
        batch_op.drop_index('ix_accessories_sku')
        batch_op.create_index(batch_op.f('ix_accessories_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_count_in_stock'), ['count_in_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_subcategory'), ['subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_variant_sku'), ['variant_sku'], unique=True)

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_sku', sa.String(length=100), nullable=False))
        batch_op.drop_index('ix_clothing_sku')
        batch_op.create_index(batch_op.f('ix_clothing_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_count_in_stock'), ['count_in_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_subcategory'), ['subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_variant_sku'), ['variant_sku'], unique=True)

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_sku', sa.String(length=100), nullable=False))
        batch_op.drop_index('ix_shoes_sku')
        batch_op.create_index(batch_op.f('ix_shoes_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_count_in_stock'), ['count_in_stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_subcategory'), ['subcategory'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_variant_sku'), ['variant_sku'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shoes_variant_sku'))
        batch_op.drop_index(batch_op.f('ix_shoes_subcategory'))
        batch_op.drop_index(batch_op.f('ix_shoes_price'))
        batch_op.drop_index(batch_op.f('ix_shoes_count_in_stock'))
        batch_op.drop_index(batch_op.f('ix_shoes_color'))
        batch_op.drop_index(batch_op.f('ix_shoes_brand'))
        batch_op.drop_index(batch_op.f('ix_shoes_sku'))
        batch_op.create_index('ix_shoes_sku', ['sku'], unique=False)
        batch_op.drop_column('variant_sku')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clothing_variant_sku'))
        batch_op.drop_index(batch_op.f('ix_clothing_subcategory'))
        batch_op.drop_index(batch_op.f('ix_clothing_price'))
        batch_op.drop_index(batch_op.f('ix_clothing_count_in_stock'))
        batch_op.drop_index(batch_op.f('ix_clothing_color'))
        batch_op.drop_index(batch_op.f('ix_clothing_brand'))
        batch_op.drop_index(batch_op.f('ix_clothing_sku'))
        batch_op.create_index('ix_clothing_sku', ['sku'], unique=False)
        batch_op.drop_column('variant_sku')

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accessories_variant_sku'))
        batch_op.drop_index(batch_op.f('ix_accessories_subcategory'))
        batch_op.drop_index(batch_op.f('ix_accessories_price'))
        batch_op.drop_index(batch_op.f('ix_accessories_count_in_stock'))
        batch_op.drop_index(batch_op.f('ix_accessories_color'))
        batch_op.drop_index(batch_op.f('ix_accessories_brand'))
        batch_op.drop_index(batch_op.f('ix_accessories_sku'))
        batch_op.create_index('ix_accessories_sku', ['sku'], unique=False)
        batch_op.drop_column('variant_sku')

    # ### end Alembic commands ###
