"""edit column name image_path

Revision ID: c6d67282d1d9
Revises: 6a1f9c764c05
Create Date: 2025-05-30 17:37:00.162630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d67282d1d9'
down_revision = '6a1f9c764c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_images', sa.Integer(), nullable=True))
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_images', sa.Integer(), nullable=True))
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_images', sa.Integer(), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('count_images')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('count_images')

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('count_images')

    # ### end Alembic commands ###
