"""correcting current settings and adding new columns

Revision ID: dd5e558261b3
Revises: 8f6c7fc475cf
Create Date: 2025-06-21 23:34:09.051637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd5e558261b3'
down_revision = '8f6c7fc475cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('world_sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('count_sales', sa.Integer(), nullable=False))
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('size_guide_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_accessories_color_sku'), ['color_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_accessories_world_sku'), ['world_sku'], unique=False)
        batch_op.drop_column('delivery_time')

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('world_sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('count_sales', sa.Integer(), nullable=False))
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('size_guide_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_clothing_color_sku'), ['color_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_world_sku'), ['world_sku'], unique=False)
        batch_op.drop_column('delivery_time')

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('world_sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('count_sales', sa.Integer(), nullable=False))
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('size_guide_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_shoes_color_sku'), ['color_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_shoes_world_sku'), ['world_sku'], unique=False)
        batch_op.drop_column('delivery_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_shoes_world_sku'))
        batch_op.drop_index(batch_op.f('ix_shoes_color_sku'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('size_guide_url',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('count_sales')
        batch_op.drop_column('world_sku')
        batch_op.drop_column('color_sku')

    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_clothing_world_sku'))
        batch_op.drop_index(batch_op.f('ix_clothing_color_sku'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('size_guide_url',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('count_sales')
        batch_op.drop_column('world_sku')
        batch_op.drop_column('color_sku')

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_accessories_world_sku'))
        batch_op.drop_index(batch_op.f('ix_accessories_color_sku'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('size_guide_url',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('count_sales')
        batch_op.drop_column('world_sku')
        batch_op.drop_column('color_sku')

    # ### end Alembic commands ###
